<?php
/**
 * DocumentsApi
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ONIX API
 *
 * Dokumentácia ku Web API programu ONIX.  Pre testovanie s reálnymi dátami (dotazovanie servera) je potrebné zadať autorizačný token, ktorý Vám poskytla firma Kros a.s..  Pri každom dotaze je potrebné uviesť cestu ku databáze s dátami (taktiež poskytnutú firmou Kros a.s.).
 *
 * The version of the OpenAPI document: V1
 * Contact: servis.onix@kros.sk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * DocumentsApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DocumentsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation documentsAddOrEditDocument
     *
     * Pridá jeden doklad, do konkrétnej evidencie dokladov určenej podľa parametra documentTypeId. Dáta dokladu sa nachádzajú v \&quot;body\&quot; requestu.  V prípade, že pridávaný doklad už existuje vykoná sa akcia edit a prebehne aktualizácia údajov na hlavičke dokladu.   V prípade, že budú v dotaze odoslané aj položky tak všetky pôvodné sú zmazané a nahradené novými.
     *
     * @param  int $document_type_id ID typu dokladu (evidencie) v obchodnom cykle. (required)
     * @param  string $database_path Cesta ku zdrojovej ONIX databáze. (required)
     * @param  \OpenAPI\Client\Model\DtoDocumentPost $document Dáta dokladu. (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Result
     */
    public function documentsAddOrEditDocument($document_type_id, $database_path, $document)
    {
        list($response) = $this->documentsAddOrEditDocumentWithHttpInfo($document_type_id, $database_path, $document);
        return $response;
    }

    /**
     * Operation documentsAddOrEditDocumentWithHttpInfo
     *
     * Pridá jeden doklad, do konkrétnej evidencie dokladov určenej podľa parametra documentTypeId. Dáta dokladu sa nachádzajú v \&quot;body\&quot; requestu.  V prípade, že pridávaný doklad už existuje vykoná sa akcia edit a prebehne aktualizácia údajov na hlavičke dokladu.   V prípade, že budú v dotaze odoslané aj položky tak všetky pôvodné sú zmazané a nahradené novými.
     *
     * @param  int $document_type_id ID typu dokladu (evidencie) v obchodnom cykle. (required)
     * @param  string $database_path Cesta ku zdrojovej ONIX databáze. (required)
     * @param  \OpenAPI\Client\Model\DtoDocumentPost $document Dáta dokladu. (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Result, HTTP status code, HTTP response headers (array of strings)
     */
    public function documentsAddOrEditDocumentWithHttpInfo($document_type_id, $database_path, $document)
    {
        $request = $this->documentsAddOrEditDocumentRequest($document_type_id, $database_path, $document);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\Result' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\Result', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\Result';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Result',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation documentsAddOrEditDocumentAsync
     *
     * Pridá jeden doklad, do konkrétnej evidencie dokladov určenej podľa parametra documentTypeId. Dáta dokladu sa nachádzajú v \&quot;body\&quot; requestu.  V prípade, že pridávaný doklad už existuje vykoná sa akcia edit a prebehne aktualizácia údajov na hlavičke dokladu.   V prípade, že budú v dotaze odoslané aj položky tak všetky pôvodné sú zmazané a nahradené novými.
     *
     * @param  int $document_type_id ID typu dokladu (evidencie) v obchodnom cykle. (required)
     * @param  string $database_path Cesta ku zdrojovej ONIX databáze. (required)
     * @param  \OpenAPI\Client\Model\DtoDocumentPost $document Dáta dokladu. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function documentsAddOrEditDocumentAsync($document_type_id, $database_path, $document)
    {
        return $this->documentsAddOrEditDocumentAsyncWithHttpInfo($document_type_id, $database_path, $document)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation documentsAddOrEditDocumentAsyncWithHttpInfo
     *
     * Pridá jeden doklad, do konkrétnej evidencie dokladov určenej podľa parametra documentTypeId. Dáta dokladu sa nachádzajú v \&quot;body\&quot; requestu.  V prípade, že pridávaný doklad už existuje vykoná sa akcia edit a prebehne aktualizácia údajov na hlavičke dokladu.   V prípade, že budú v dotaze odoslané aj položky tak všetky pôvodné sú zmazané a nahradené novými.
     *
     * @param  int $document_type_id ID typu dokladu (evidencie) v obchodnom cykle. (required)
     * @param  string $database_path Cesta ku zdrojovej ONIX databáze. (required)
     * @param  \OpenAPI\Client\Model\DtoDocumentPost $document Dáta dokladu. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function documentsAddOrEditDocumentAsyncWithHttpInfo($document_type_id, $database_path, $document)
    {
        $returnType = '\OpenAPI\Client\Model\Result';
        $request = $this->documentsAddOrEditDocumentRequest($document_type_id, $database_path, $document);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'documentsAddOrEditDocument'
     *
     * @param  int $document_type_id ID typu dokladu (evidencie) v obchodnom cykle. (required)
     * @param  string $database_path Cesta ku zdrojovej ONIX databáze. (required)
     * @param  \OpenAPI\Client\Model\DtoDocumentPost $document Dáta dokladu. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function documentsAddOrEditDocumentRequest($document_type_id, $database_path, $document)
    {
        // verify the required parameter 'document_type_id' is set
        if ($document_type_id === null || (is_array($document_type_id) && count($document_type_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $document_type_id when calling documentsAddOrEditDocument'
            );
        }
        // verify the required parameter 'database_path' is set
        if ($database_path === null || (is_array($database_path) && count($database_path) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $database_path when calling documentsAddOrEditDocument'
            );
        }
        // verify the required parameter 'document' is set
        if ($document === null || (is_array($document) && count($document) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $document when calling documentsAddOrEditDocument'
            );
        }

        $resourcePath = '/api/v1/documents/{documentTypeId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($database_path !== null) {
            $headerParams['DatabasePath'] = ObjectSerializer::toHeaderValue($database_path);
        }

        // path params
        if ($document_type_id !== null) {
            $resourcePath = str_replace(
                '{' . 'documentTypeId' . '}',
                ObjectSerializer::toPathValue($document_type_id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json', 'application/xml', 'text/xml']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json', 'application/xml', 'text/xml'],
                ['application/json', 'text/json', 'application/xml', 'text/xml', 'application/x-www-form-urlencoded']
            );
        }

        // for model (json/xml)
        if (isset($document)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($document));
            } else {
                $httpBody = $document;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation documentsAddOrEditDocuments
     *
     * Pridá viacero dokladov, do konkrétnej evidencie dokladov určenej podľa parametra documentTypeId. Dáta dokladov sa nachádzajú v \&quot;body\&quot; requestu.
     *
     * @param  int $document_type_id ID typu dokladu (evidencie) v obchodnom cykle. (required)
     * @param  string $database_path Cesta ku zdrojovej ONIX databáze. (required)
     * @param  \OpenAPI\Client\Model\DtoDocumentPost[] $documents Dáta dokladov. (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Result[]
     */
    public function documentsAddOrEditDocuments($document_type_id, $database_path, $documents)
    {
        list($response) = $this->documentsAddOrEditDocumentsWithHttpInfo($document_type_id, $database_path, $documents);
        return $response;
    }

    /**
     * Operation documentsAddOrEditDocumentsWithHttpInfo
     *
     * Pridá viacero dokladov, do konkrétnej evidencie dokladov určenej podľa parametra documentTypeId. Dáta dokladov sa nachádzajú v \&quot;body\&quot; requestu.
     *
     * @param  int $document_type_id ID typu dokladu (evidencie) v obchodnom cykle. (required)
     * @param  string $database_path Cesta ku zdrojovej ONIX databáze. (required)
     * @param  \OpenAPI\Client\Model\DtoDocumentPost[] $documents Dáta dokladov. (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Result[], HTTP status code, HTTP response headers (array of strings)
     */
    public function documentsAddOrEditDocumentsWithHttpInfo($document_type_id, $database_path, $documents)
    {
        $request = $this->documentsAddOrEditDocumentsRequest($document_type_id, $database_path, $documents);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\Result[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\Result[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\Result[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Result[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation documentsAddOrEditDocumentsAsync
     *
     * Pridá viacero dokladov, do konkrétnej evidencie dokladov určenej podľa parametra documentTypeId. Dáta dokladov sa nachádzajú v \&quot;body\&quot; requestu.
     *
     * @param  int $document_type_id ID typu dokladu (evidencie) v obchodnom cykle. (required)
     * @param  string $database_path Cesta ku zdrojovej ONIX databáze. (required)
     * @param  \OpenAPI\Client\Model\DtoDocumentPost[] $documents Dáta dokladov. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function documentsAddOrEditDocumentsAsync($document_type_id, $database_path, $documents)
    {
        return $this->documentsAddOrEditDocumentsAsyncWithHttpInfo($document_type_id, $database_path, $documents)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation documentsAddOrEditDocumentsAsyncWithHttpInfo
     *
     * Pridá viacero dokladov, do konkrétnej evidencie dokladov určenej podľa parametra documentTypeId. Dáta dokladov sa nachádzajú v \&quot;body\&quot; requestu.
     *
     * @param  int $document_type_id ID typu dokladu (evidencie) v obchodnom cykle. (required)
     * @param  string $database_path Cesta ku zdrojovej ONIX databáze. (required)
     * @param  \OpenAPI\Client\Model\DtoDocumentPost[] $documents Dáta dokladov. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function documentsAddOrEditDocumentsAsyncWithHttpInfo($document_type_id, $database_path, $documents)
    {
        $returnType = '\OpenAPI\Client\Model\Result[]';
        $request = $this->documentsAddOrEditDocumentsRequest($document_type_id, $database_path, $documents);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'documentsAddOrEditDocuments'
     *
     * @param  int $document_type_id ID typu dokladu (evidencie) v obchodnom cykle. (required)
     * @param  string $database_path Cesta ku zdrojovej ONIX databáze. (required)
     * @param  \OpenAPI\Client\Model\DtoDocumentPost[] $documents Dáta dokladov. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function documentsAddOrEditDocumentsRequest($document_type_id, $database_path, $documents)
    {
        // verify the required parameter 'document_type_id' is set
        if ($document_type_id === null || (is_array($document_type_id) && count($document_type_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $document_type_id when calling documentsAddOrEditDocuments'
            );
        }
        // verify the required parameter 'database_path' is set
        if ($database_path === null || (is_array($database_path) && count($database_path) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $database_path when calling documentsAddOrEditDocuments'
            );
        }
        // verify the required parameter 'documents' is set
        if ($documents === null || (is_array($documents) && count($documents) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $documents when calling documentsAddOrEditDocuments'
            );
        }

        $resourcePath = '/api/v1/documents/{documentTypeId}/list';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($database_path !== null) {
            $headerParams['DatabasePath'] = ObjectSerializer::toHeaderValue($database_path);
        }

        // path params
        if ($document_type_id !== null) {
            $resourcePath = str_replace(
                '{' . 'documentTypeId' . '}',
                ObjectSerializer::toPathValue($document_type_id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json', 'application/xml', 'text/xml']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json', 'application/xml', 'text/xml'],
                ['application/json', 'text/json', 'application/xml', 'text/xml', 'application/x-www-form-urlencoded']
            );
        }

        // for model (json/xml)
        if (isset($documents)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($documents));
            } else {
                $httpBody = $documents;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation documentsDeleteDocuments
     *
     * Vymaže doklad. Doklad je určený na základe čísla, kódu číselného radu a kódu evidencie.
     *
     * @param  int $document_type_id ID typu dokladu (evidencie) v obchodnom cykle. (required)
     * @param  string $ns_number Číslo dokladu. (required)
     * @param  string $ns_code Kód číselného radu. (required)
     * @param  string $ns_evid_code Kód evidencie. (required)
     * @param  string $database_path Cesta ku zdrojovej ONIX databáze. (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Result
     */
    public function documentsDeleteDocuments($document_type_id, $ns_number, $ns_code, $ns_evid_code, $database_path)
    {
        list($response) = $this->documentsDeleteDocumentsWithHttpInfo($document_type_id, $ns_number, $ns_code, $ns_evid_code, $database_path);
        return $response;
    }

    /**
     * Operation documentsDeleteDocumentsWithHttpInfo
     *
     * Vymaže doklad. Doklad je určený na základe čísla, kódu číselného radu a kódu evidencie.
     *
     * @param  int $document_type_id ID typu dokladu (evidencie) v obchodnom cykle. (required)
     * @param  string $ns_number Číslo dokladu. (required)
     * @param  string $ns_code Kód číselného radu. (required)
     * @param  string $ns_evid_code Kód evidencie. (required)
     * @param  string $database_path Cesta ku zdrojovej ONIX databáze. (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Result, HTTP status code, HTTP response headers (array of strings)
     */
    public function documentsDeleteDocumentsWithHttpInfo($document_type_id, $ns_number, $ns_code, $ns_evid_code, $database_path)
    {
        $request = $this->documentsDeleteDocumentsRequest($document_type_id, $ns_number, $ns_code, $ns_evid_code, $database_path);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\Result' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\Result', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\Result';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Result',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation documentsDeleteDocumentsAsync
     *
     * Vymaže doklad. Doklad je určený na základe čísla, kódu číselného radu a kódu evidencie.
     *
     * @param  int $document_type_id ID typu dokladu (evidencie) v obchodnom cykle. (required)
     * @param  string $ns_number Číslo dokladu. (required)
     * @param  string $ns_code Kód číselného radu. (required)
     * @param  string $ns_evid_code Kód evidencie. (required)
     * @param  string $database_path Cesta ku zdrojovej ONIX databáze. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function documentsDeleteDocumentsAsync($document_type_id, $ns_number, $ns_code, $ns_evid_code, $database_path)
    {
        return $this->documentsDeleteDocumentsAsyncWithHttpInfo($document_type_id, $ns_number, $ns_code, $ns_evid_code, $database_path)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation documentsDeleteDocumentsAsyncWithHttpInfo
     *
     * Vymaže doklad. Doklad je určený na základe čísla, kódu číselného radu a kódu evidencie.
     *
     * @param  int $document_type_id ID typu dokladu (evidencie) v obchodnom cykle. (required)
     * @param  string $ns_number Číslo dokladu. (required)
     * @param  string $ns_code Kód číselného radu. (required)
     * @param  string $ns_evid_code Kód evidencie. (required)
     * @param  string $database_path Cesta ku zdrojovej ONIX databáze. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function documentsDeleteDocumentsAsyncWithHttpInfo($document_type_id, $ns_number, $ns_code, $ns_evid_code, $database_path)
    {
        $returnType = '\OpenAPI\Client\Model\Result';
        $request = $this->documentsDeleteDocumentsRequest($document_type_id, $ns_number, $ns_code, $ns_evid_code, $database_path);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'documentsDeleteDocuments'
     *
     * @param  int $document_type_id ID typu dokladu (evidencie) v obchodnom cykle. (required)
     * @param  string $ns_number Číslo dokladu. (required)
     * @param  string $ns_code Kód číselného radu. (required)
     * @param  string $ns_evid_code Kód evidencie. (required)
     * @param  string $database_path Cesta ku zdrojovej ONIX databáze. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function documentsDeleteDocumentsRequest($document_type_id, $ns_number, $ns_code, $ns_evid_code, $database_path)
    {
        // verify the required parameter 'document_type_id' is set
        if ($document_type_id === null || (is_array($document_type_id) && count($document_type_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $document_type_id when calling documentsDeleteDocuments'
            );
        }
        // verify the required parameter 'ns_number' is set
        if ($ns_number === null || (is_array($ns_number) && count($ns_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ns_number when calling documentsDeleteDocuments'
            );
        }
        // verify the required parameter 'ns_code' is set
        if ($ns_code === null || (is_array($ns_code) && count($ns_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ns_code when calling documentsDeleteDocuments'
            );
        }
        // verify the required parameter 'ns_evid_code' is set
        if ($ns_evid_code === null || (is_array($ns_evid_code) && count($ns_evid_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ns_evid_code when calling documentsDeleteDocuments'
            );
        }
        // verify the required parameter 'database_path' is set
        if ($database_path === null || (is_array($database_path) && count($database_path) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $database_path when calling documentsDeleteDocuments'
            );
        }

        $resourcePath = '/api/v1/documents/{documentTypeId}/{nsNumber}/{nsCode}/{nsEvidCode}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($database_path !== null) {
            $headerParams['DatabasePath'] = ObjectSerializer::toHeaderValue($database_path);
        }

        // path params
        if ($document_type_id !== null) {
            $resourcePath = str_replace(
                '{' . 'documentTypeId' . '}',
                ObjectSerializer::toPathValue($document_type_id),
                $resourcePath
            );
        }
        // path params
        if ($ns_number !== null) {
            $resourcePath = str_replace(
                '{' . 'nsNumber' . '}',
                ObjectSerializer::toPathValue($ns_number),
                $resourcePath
            );
        }
        // path params
        if ($ns_code !== null) {
            $resourcePath = str_replace(
                '{' . 'nsCode' . '}',
                ObjectSerializer::toPathValue($ns_code),
                $resourcePath
            );
        }
        // path params
        if ($ns_evid_code !== null) {
            $resourcePath = str_replace(
                '{' . 'nsEvidCode' . '}',
                ObjectSerializer::toPathValue($ns_evid_code),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json', 'application/xml', 'text/xml']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json', 'application/xml', 'text/xml'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation documentsGetDocuments
     *
     * Vracia zoznam všetkých dokumentov, z konkrétnej evidencie. Evidencia je určená na základe parametra documentTypeId.
     *
     * @param  int $document_type_id ID typu dokladu (evidencie) v obchodnom cykle. (required)
     * @param  string $database_path Cesta ku zdrojovej ONIX databáze. (required)
     * @param  string[] $tables Zoznam podtabuliek dokladu&lt;br&gt;ALL - všetky podtabuľky&lt;br&gt;DOCITEMS - položky&lt;br&gt;ENCLOSURES - prílohy (optional)
     * @param  string $partner_name Filter: Názov partnera   Ako filter je možné použiť, ktorékoľvek pole z modelu. (optional)
     * @param  string $ns_number Filter: Číslo dokladu   Ako filter je možné použiť, ktorékoľvek pole z modelu. (optional)
     * @param  string $select Definovanie polí, ktoré majú byť vo výsledku volania (JSON). Zadávajte ako názvy stĺpcov z modelu oddelené čiarkou. V prípade podzáznamov tabuľky zadávajte ako NazovPodtabulky.NazovPola. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\DtoDocumentGet[]
     */
    public function documentsGetDocuments($document_type_id, $database_path, $tables = null, $partner_name = null, $ns_number = null, $select = null)
    {
        list($response) = $this->documentsGetDocumentsWithHttpInfo($document_type_id, $database_path, $tables, $partner_name, $ns_number, $select);
        return $response;
    }

    /**
     * Operation documentsGetDocumentsWithHttpInfo
     *
     * Vracia zoznam všetkých dokumentov, z konkrétnej evidencie. Evidencia je určená na základe parametra documentTypeId.
     *
     * @param  int $document_type_id ID typu dokladu (evidencie) v obchodnom cykle. (required)
     * @param  string $database_path Cesta ku zdrojovej ONIX databáze. (required)
     * @param  string[] $tables Zoznam podtabuliek dokladu&lt;br&gt;ALL - všetky podtabuľky&lt;br&gt;DOCITEMS - položky&lt;br&gt;ENCLOSURES - prílohy (optional)
     * @param  string $partner_name Filter: Názov partnera   Ako filter je možné použiť, ktorékoľvek pole z modelu. (optional)
     * @param  string $ns_number Filter: Číslo dokladu   Ako filter je možné použiť, ktorékoľvek pole z modelu. (optional)
     * @param  string $select Definovanie polí, ktoré majú byť vo výsledku volania (JSON). Zadávajte ako názvy stĺpcov z modelu oddelené čiarkou. V prípade podzáznamov tabuľky zadávajte ako NazovPodtabulky.NazovPola. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\DtoDocumentGet[], HTTP status code, HTTP response headers (array of strings)
     */
    public function documentsGetDocumentsWithHttpInfo($document_type_id, $database_path, $tables = null, $partner_name = null, $ns_number = null, $select = null)
    {
        $request = $this->documentsGetDocumentsRequest($document_type_id, $database_path, $tables, $partner_name, $ns_number, $select);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\DtoDocumentGet[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\DtoDocumentGet[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\DtoDocumentGet[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\DtoDocumentGet[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation documentsGetDocumentsAsync
     *
     * Vracia zoznam všetkých dokumentov, z konkrétnej evidencie. Evidencia je určená na základe parametra documentTypeId.
     *
     * @param  int $document_type_id ID typu dokladu (evidencie) v obchodnom cykle. (required)
     * @param  string $database_path Cesta ku zdrojovej ONIX databáze. (required)
     * @param  string[] $tables Zoznam podtabuliek dokladu&lt;br&gt;ALL - všetky podtabuľky&lt;br&gt;DOCITEMS - položky&lt;br&gt;ENCLOSURES - prílohy (optional)
     * @param  string $partner_name Filter: Názov partnera   Ako filter je možné použiť, ktorékoľvek pole z modelu. (optional)
     * @param  string $ns_number Filter: Číslo dokladu   Ako filter je možné použiť, ktorékoľvek pole z modelu. (optional)
     * @param  string $select Definovanie polí, ktoré majú byť vo výsledku volania (JSON). Zadávajte ako názvy stĺpcov z modelu oddelené čiarkou. V prípade podzáznamov tabuľky zadávajte ako NazovPodtabulky.NazovPola. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function documentsGetDocumentsAsync($document_type_id, $database_path, $tables = null, $partner_name = null, $ns_number = null, $select = null)
    {
        return $this->documentsGetDocumentsAsyncWithHttpInfo($document_type_id, $database_path, $tables, $partner_name, $ns_number, $select)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation documentsGetDocumentsAsyncWithHttpInfo
     *
     * Vracia zoznam všetkých dokumentov, z konkrétnej evidencie. Evidencia je určená na základe parametra documentTypeId.
     *
     * @param  int $document_type_id ID typu dokladu (evidencie) v obchodnom cykle. (required)
     * @param  string $database_path Cesta ku zdrojovej ONIX databáze. (required)
     * @param  string[] $tables Zoznam podtabuliek dokladu&lt;br&gt;ALL - všetky podtabuľky&lt;br&gt;DOCITEMS - položky&lt;br&gt;ENCLOSURES - prílohy (optional)
     * @param  string $partner_name Filter: Názov partnera   Ako filter je možné použiť, ktorékoľvek pole z modelu. (optional)
     * @param  string $ns_number Filter: Číslo dokladu   Ako filter je možné použiť, ktorékoľvek pole z modelu. (optional)
     * @param  string $select Definovanie polí, ktoré majú byť vo výsledku volania (JSON). Zadávajte ako názvy stĺpcov z modelu oddelené čiarkou. V prípade podzáznamov tabuľky zadávajte ako NazovPodtabulky.NazovPola. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function documentsGetDocumentsAsyncWithHttpInfo($document_type_id, $database_path, $tables = null, $partner_name = null, $ns_number = null, $select = null)
    {
        $returnType = '\OpenAPI\Client\Model\DtoDocumentGet[]';
        $request = $this->documentsGetDocumentsRequest($document_type_id, $database_path, $tables, $partner_name, $ns_number, $select);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'documentsGetDocuments'
     *
     * @param  int $document_type_id ID typu dokladu (evidencie) v obchodnom cykle. (required)
     * @param  string $database_path Cesta ku zdrojovej ONIX databáze. (required)
     * @param  string[] $tables Zoznam podtabuliek dokladu&lt;br&gt;ALL - všetky podtabuľky&lt;br&gt;DOCITEMS - položky&lt;br&gt;ENCLOSURES - prílohy (optional)
     * @param  string $partner_name Filter: Názov partnera   Ako filter je možné použiť, ktorékoľvek pole z modelu. (optional)
     * @param  string $ns_number Filter: Číslo dokladu   Ako filter je možné použiť, ktorékoľvek pole z modelu. (optional)
     * @param  string $select Definovanie polí, ktoré majú byť vo výsledku volania (JSON). Zadávajte ako názvy stĺpcov z modelu oddelené čiarkou. V prípade podzáznamov tabuľky zadávajte ako NazovPodtabulky.NazovPola. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function documentsGetDocumentsRequest($document_type_id, $database_path, $tables = null, $partner_name = null, $ns_number = null, $select = null)
    {
        // verify the required parameter 'document_type_id' is set
        if ($document_type_id === null || (is_array($document_type_id) && count($document_type_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $document_type_id when calling documentsGetDocuments'
            );
        }
        // verify the required parameter 'database_path' is set
        if ($database_path === null || (is_array($database_path) && count($database_path) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $database_path when calling documentsGetDocuments'
            );
        }

        $resourcePath = '/api/v1/documents/{documentTypeId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($tables !== null) {
            if('form' === 'form' && is_array($tables)) {
                foreach($tables as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['tables'] = $tables;
            }
        }
        // query params
        if (is_array($partner_name)) {
            $partner_name = ObjectSerializer::serializeCollection($partner_name, '', true);
        }
        if ($partner_name !== null) {
            $queryParams['Partner_Name'] = $partner_name;
        }
        // query params
        if (is_array($ns_number)) {
            $ns_number = ObjectSerializer::serializeCollection($ns_number, '', true);
        }
        if ($ns_number !== null) {
            $queryParams['Ns_Number'] = $ns_number;
        }
        // query params
        if (is_array($select)) {
            $select = ObjectSerializer::serializeCollection($select, '', true);
        }
        if ($select !== null) {
            $queryParams['$select'] = $select;
        }

        // header params
        if ($database_path !== null) {
            $headerParams['DatabasePath'] = ObjectSerializer::toHeaderValue($database_path);
        }

        // path params
        if ($document_type_id !== null) {
            $resourcePath = str_replace(
                '{' . 'documentTypeId' . '}',
                ObjectSerializer::toPathValue($document_type_id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json', 'application/xml', 'text/xml']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json', 'application/xml', 'text/xml'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
