<?php
/**
 * DtoInternalAccounting
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ONIX API
 *
 * Dokumentácia ku Web API programu ONIX.  Pre testovanie s reálnymi dátami (dotazovanie servera) je potrebné zadať autorizačný token, ktorý Vám poskytla firma Kros a.s..  Pri každom dotaze je potrebné uviesť cestu ku databáze s dátami (taktiež poskytnutú firmou Kros a.s.).
 *
 * The version of the OpenAPI document: V1
 * Contact: servis.onix@kros.sk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * DtoInternalAccounting Class Doc Comment
 *
 * @category Class
 * @description DTO trieda pre interné rozúčtovanie.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class DtoInternalAccounting implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DtoInternalAccounting';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id_record' => 'int',
        'variant' => 'int',
        'id_parent' => 'int',
        'tree_parents' => 'string',
        'tree_level' => 'int',
        'ordinal' => 'int',
        'name' => 'string',
        'is_breakdown' => 'int',
        'code' => 'string',
        'ns_code' => 'string',
        'ns_evid_code' => 'string',
        'ns_number' => 'string',
        'custom_columns' => '\OpenAPI\Client\Model\CustomField[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id_record' => 'int64',
        'variant' => 'int32',
        'id_parent' => 'int64',
        'tree_parents' => null,
        'tree_level' => 'int32',
        'ordinal' => 'int32',
        'name' => null,
        'is_breakdown' => 'int32',
        'code' => null,
        'ns_code' => null,
        'ns_evid_code' => null,
        'ns_number' => null,
        'custom_columns' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id_record' => 'IdRecord',
        'variant' => 'Variant',
        'id_parent' => 'Id_Parent',
        'tree_parents' => 'Tree_Parents',
        'tree_level' => 'Tree_Level',
        'ordinal' => 'Ordinal',
        'name' => 'Name',
        'is_breakdown' => 'Is_Breakdown',
        'code' => 'Code',
        'ns_code' => 'Ns_Code',
        'ns_evid_code' => 'Ns_Evid_Code',
        'ns_number' => 'Ns_Number',
        'custom_columns' => 'CustomColumns'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id_record' => 'setIdRecord',
        'variant' => 'setVariant',
        'id_parent' => 'setIdParent',
        'tree_parents' => 'setTreeParents',
        'tree_level' => 'setTreeLevel',
        'ordinal' => 'setOrdinal',
        'name' => 'setName',
        'is_breakdown' => 'setIsBreakdown',
        'code' => 'setCode',
        'ns_code' => 'setNsCode',
        'ns_evid_code' => 'setNsEvidCode',
        'ns_number' => 'setNsNumber',
        'custom_columns' => 'setCustomColumns'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id_record' => 'getIdRecord',
        'variant' => 'getVariant',
        'id_parent' => 'getIdParent',
        'tree_parents' => 'getTreeParents',
        'tree_level' => 'getTreeLevel',
        'ordinal' => 'getOrdinal',
        'name' => 'getName',
        'is_breakdown' => 'getIsBreakdown',
        'code' => 'getCode',
        'ns_code' => 'getNsCode',
        'ns_evid_code' => 'getNsEvidCode',
        'ns_number' => 'getNsNumber',
        'custom_columns' => 'getCustomColumns'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id_record'] = $data['id_record'] ?? null;
        $this->container['variant'] = $data['variant'] ?? null;
        $this->container['id_parent'] = $data['id_parent'] ?? null;
        $this->container['tree_parents'] = $data['tree_parents'] ?? null;
        $this->container['tree_level'] = $data['tree_level'] ?? null;
        $this->container['ordinal'] = $data['ordinal'] ?? null;
        $this->container['name'] = $data['name'] ?? null;
        $this->container['is_breakdown'] = $data['is_breakdown'] ?? null;
        $this->container['code'] = $data['code'] ?? null;
        $this->container['ns_code'] = $data['ns_code'] ?? null;
        $this->container['ns_evid_code'] = $data['ns_evid_code'] ?? null;
        $this->container['ns_number'] = $data['ns_number'] ?? null;
        $this->container['custom_columns'] = $data['custom_columns'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id_record
     *
     * @return int|null
     */
    public function getIdRecord()
    {
        return $this->container['id_record'];
    }

    /**
     * Sets id_record
     *
     * @param int|null $id_record ID záznamu
     *
     * @return self
     */
    public function setIdRecord($id_record)
    {
        $this->container['id_record'] = $id_record;

        return $this;
    }

    /**
     * Gets variant
     *
     * @return int|null
     */
    public function getVariant()
    {
        return $this->container['variant'];
    }

    /**
     * Sets variant
     *
     * @param int|null $variant Variant interného rozúčtovania
     *
     * @return self
     */
    public function setVariant($variant)
    {
        $this->container['variant'] = $variant;

        return $this;
    }

    /**
     * Gets id_parent
     *
     * @return int|null
     */
    public function getIdParent()
    {
        return $this->container['id_parent'];
    }

    /**
     * Sets id_parent
     *
     * @param int|null $id_parent IdRecord nadradenej hodnoty v strome
     *
     * @return self
     */
    public function setIdParent($id_parent)
    {
        $this->container['id_parent'] = $id_parent;

        return $this;
    }

    /**
     * Gets tree_parents
     *
     * @return string|null
     */
    public function getTreeParents()
    {
        return $this->container['tree_parents'];
    }

    /**
     * Sets tree_parents
     *
     * @param string|null $tree_parents Strom - Zoznam predchodcov
     *
     * @return self
     */
    public function setTreeParents($tree_parents)
    {
        $this->container['tree_parents'] = $tree_parents;

        return $this;
    }

    /**
     * Gets tree_level
     *
     * @return int|null
     */
    public function getTreeLevel()
    {
        return $this->container['tree_level'];
    }

    /**
     * Sets tree_level
     *
     * @param int|null $tree_level Strom - Úroveň
     *
     * @return self
     */
    public function setTreeLevel($tree_level)
    {
        $this->container['tree_level'] = $tree_level;

        return $this;
    }

    /**
     * Gets ordinal
     *
     * @return int|null
     */
    public function getOrdinal()
    {
        return $this->container['ordinal'];
    }

    /**
     * Sets ordinal
     *
     * @param int|null $ordinal Poradové číslo
     *
     * @return self
     */
    public function setOrdinal($ordinal)
    {
        $this->container['ordinal'] = $ordinal;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Názov (stĺpec je možné použiť na filtrovanie)
     *
     * @return self
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets is_breakdown
     *
     * @return int|null
     */
    public function getIsBreakdown()
    {
        return $this->container['is_breakdown'];
    }

    /**
     * Sets is_breakdown
     *
     * @param int|null $is_breakdown Interné rozúčtovanie je rozpis (-1 znamená, že ide o rozpis, 0 znamená, že nejde o rozpis)
     *
     * @return self
     */
    public function setIsBreakdown($is_breakdown)
    {
        $this->container['is_breakdown'] = $is_breakdown;

        return $this;
    }

    /**
     * Gets code
     *
     * @return string|null
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string|null $code Kód interného rozúčtovania (stĺpec je možné použiť na filtrovanie)
     *
     * @return self
     */
    public function setCode($code)
    {
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets ns_code
     *
     * @return string|null
     */
    public function getNsCode()
    {
        return $this->container['ns_code'];
    }

    /**
     * Sets ns_code
     *
     * @param string|null $ns_code Kód číselného radu (stĺpec je možné použiť na filtrovanie)
     *
     * @return self
     */
    public function setNsCode($ns_code)
    {
        $this->container['ns_code'] = $ns_code;

        return $this;
    }

    /**
     * Gets ns_evid_code
     *
     * @return string|null
     */
    public function getNsEvidCode()
    {
        return $this->container['ns_evid_code'];
    }

    /**
     * Sets ns_evid_code
     *
     * @param string|null $ns_evid_code Kód evidencie (stĺpec je možné použiť na filtrovanie)
     *
     * @return self
     */
    public function setNsEvidCode($ns_evid_code)
    {
        $this->container['ns_evid_code'] = $ns_evid_code;

        return $this;
    }

    /**
     * Gets ns_number
     *
     * @return string|null
     */
    public function getNsNumber()
    {
        return $this->container['ns_number'];
    }

    /**
     * Sets ns_number
     *
     * @param string|null $ns_number Číslo (stĺpec je možné použiť na filtrovanie)
     *
     * @return self
     */
    public function setNsNumber($ns_number)
    {
        $this->container['ns_number'] = $ns_number;

        return $this;
    }

    /**
     * Gets custom_columns
     *
     * @return \OpenAPI\Client\Model\CustomField[]|null
     */
    public function getCustomColumns()
    {
        return $this->container['custom_columns'];
    }

    /**
     * Sets custom_columns
     *
     * @param \OpenAPI\Client\Model\CustomField[]|null $custom_columns custom_columns
     *
     * @return self
     */
    public function setCustomColumns($custom_columns)
    {
        $this->container['custom_columns'] = $custom_columns;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


